version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: ajmera_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ajmera_infotech
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    image: node_server
    depends_on:
      - postgres_db
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node_server
    restart: always
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/ajmera_infotech?schema=public

volumes:
  postgres_data:
  redis_data:
